FROM node:24.7.0-trixie AS builder

WORKDIR /build

COPY app/package*.json ./
RUN npm i
COPY app .
RUN npm run build 

FROM oven/bun:1.2.22-alpine

COPY --from=builder /build/.output /app

CMD ["bun", "run", "/app/server/index.mjs"]
