name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - '.dockerignore'
      - 'Dockerfile.prod'
      - '.github/workflows/deploy.yml'
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ghcr.io/hardandheavy/${{ github.event.repository.name }}:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop hardandheavy || true
            docker rm hardandheavy || true
            docker pull ghcr.io/hardandheavy/${{ github.event.repository.name }}:latest
            docker run -d \
              --name hardandheavy \
              --restart unless-stopped \
              --network=caddy-net \
              ghcr.io/hardandheavy/${{ github.event.repository.name }}:latest
